/*
 Name: Matthew Floyd
Date: 10/21/22
Program Name: EX10_Mystical6
Prompt: The mathematician Euclid
proved that there is an infinite number of prime
numbers. One of the greatest challenges to
mathematicians was to find a formula that would
generate all the prime numbers. It has been purported
that all prime numbers will be either one less than or
one greater than a multiple of 6. That is all primes
will all be either when N mod 6 equals 1 or 5,
however not every number generated by this condition
will be prime. Write a program to test this theory for
all numbers <=500
 */
using System;
using System.IO;

namespace MFEx10_Mystical6
{
    class MysticalSix
    {
        static void Main()
        {
            using (StreamWriter myWriter = new StreamWriter("Mystical6.txt")) //Opens the writer up here because it breaks if i dont
            {
                for (int i = 2; i <= 500; i++) //loops for every number through 500
                {
                    
                    if (i % 6 != 1 || i % 6 != 5)//If it is not a magical six, and not a prime
                    {
                        if (chkPrime(i) == false)
                        {
                            Console.ForegroundColor = ConsoleColor.White;
                        }
                    }


                    if (i % 6 == 1 || i % 6 == 5) //If it is a magical six, and not a prime
                    {
                        if (chkPrime(i) == false)
                        {
                            Console.ForegroundColor = ConsoleColor.Red;
                        }
                    }

                    if (i % 6 == 1 || i % 6 == 5) //If it is a magical six, and a prime
                    {
                        if (chkPrime(i))
                        {
                            Console.ForegroundColor = ConsoleColor.Magenta;

                            
                        }
                    }

                    else if (i % 6 != 1 || i % 6 != 5) //If it is not a magical six, and a prime
                    {
                        if (chkPrime(i))
                        {
                            Console.ForegroundColor = ConsoleColor.Yellow;
                        }
                    }

                    Console.WriteLine(i);
                    if (i % 6 == 1 || i % 6 == 5) //tells if the file needs to be written to
                    {

                        //Console.WriteLine("DEBUG writing {0} to file", i);
                        myWriter.Write(i + " ");

                    }
                }
            }
        }

        public static bool chkPrime(int num) //I re coded this check prime
        {
            for (int i = 2; i < num; i++)
                if (num % i == 0) //Screw curly brackets
                    return false;
            return true;
        }

    }
}
